name: Deploy development build to AWS  

on:
  push:
    branches:
      - dev 
  workflow_dispatch:

env:
  BLOG_METADATA_TABLE: ${{vars.BLOG_METADATA_TABLE}}
  BLOG_CONTENT_BUCKET: ${{vars.BLOG_CONTENT_BUCKET}}
  BLOG_ASSETS_BUCKET: ${{vars.BLOG_ASSETS_BUCKET}}
  JWT_PUBLIC_KEY: ${{vars.JWT_PUBLIC_KEY}}

jobs:
  deploy:
    name: deploy
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: "Configure AWS Credentials" Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ap-southeast-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} 
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Environment
      run: |
        npm i -g yarn
        yarn install --immutable
      
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

