name: Deploy development build to AWS

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: configure aws profile
        run: |
          aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}} --profile blog-dev
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY }} --profile blog-dev

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Environment
        run: |
          npm i -g yarn
          yarn install --immutable
      - name: Bundle with ncc
        run: |
          yarn bundle:serverless
      - name: serverless deploy
        run: |
          yarn sls deploy --stage dev --region ap-southeast-2
        env:
          AWS_SDK_LOAD_CONFIG: 1
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
          BLOG_METADATA_TABLE: ${{vars.BLOG_METADATA_TABLE}}
          BLOG_CONTENT_BUCKET: ${{vars.BLOG_CONTENT_BUCKET}}
          BLOG_ASSETS_BUCKET: ${{vars.BLOG_ASSETS_BUCKET}}
          JWT_PUBLIC_KEY: ${{vars.JWT_PUBLIC_KEY}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
