name: Terraform Apply

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # TODO: find a way to concel previous runs with SIGINT

jobs:
  apply:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # TODO: this should be from terraform
          role-to-assume: arn:aws:iam::211125712027:role/BlogDeployment-${{ env.STAGE_NAME }}
          aws-region: ap-southeast-2
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
